### ISSUE TITLE
Error with npm install after adding package.json

### ISSUE THREAD

**Issue by DakotaLMartinez** [learn-co-students/angular-using-scope-apply-lab-v-000#133]
@aturkewi 

After running `npm init` to add a package.json, running `npm install express --save` led to the following error message: 
```
Erics-MacBook-Pro:angular-using-scope-apply-lab-v-000 ericloos$ npm install express --save
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install" "express" "--save"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! path ../mime/cli.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../mime/cli.js' -> '/Users/ericloos/Code/angular-using-scope-apply-lab-v-000/node_modules/.bin/mime'
npm ERR!  { Error: EACCES: permission denied, symlink '../mime/cli.js' -> '/Users/ericloos/Code/angular-using-scope-apply-lab-v-000/node_modules/.bin/mime'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../mime/cli.js',
npm ERR!   dest: '/Users/ericloos/Code/angular-using-scope-apply-lab-v-000/node_modules/.bin/mime',
npm ERR!   parent: 'angular-using-scope-apply-lab-v-000' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ericloos/Code/angular-using-scope-apply-lab-v-000/npm-debug.
```

We tried the following: 

```
npm config get prefix
```
this returned `/usr/local` so we did
```
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

We also tried

 `brew unlink node && brew link node` 

None of those commands resolved the permissions error. Student was able to run `npm install` successfully in other projects including the ones before and after this one. He wanted to run his test suite, but was unable because of the errors with `npm install`

In the end, 

`sudo npm install` worked after we had added "express": "^4.13.4" to the `package.json` file manually.

**Comment by aturkewi** [comment]
@DakotaLMartinez thanks for raising this!

I think I totally misunderstood you earlier. I though you had said a lot of people were running into an issue here on this lab and that you had figured out a lab specific explanation. As I think everything here is specific to one user's computer, I'm actually going to close this. I

Also, just a quick FYI, it's best to raise all lab issues on the learn-co-curriculum organization. Issues raised on deploys in learn-co-students do not get tracked :(
