### ISSUE TITLE
missing package.json

### ISSUE THREAD

**Issue by pajamaw** [learn-co-students/angular-using-scope-apply-lab-v-000#17]

**Comment by fiveinfinity** [comment]
Can confirm, same problem

**Comment by the-widget** [comment]
Merge pull request #62 to resolve issue.
https://github.com/learn-co-students/angular-using-scope-apply-lab-v-000/pull/62

**Comment by theRingleman** [comment]
Again, can confirm, same exact issue, noticed throughout multiple repos.

**Comment by aprietof** [comment]
create a package.json file add this inside:

{
    "name": "angular",
    "version": "1.0.0",
    "devDependencies": {
     "express": "^4.13.4"
    }
 }

and problem solved

**Comment by DakotaLMartinez** [comment]
package.json file was added to the learn-co-curriculum/angular-using-scope-apply-lab repo, but it's still not showing up on the learn-co-students repo. Has the change been properly deployed?

**Comment by aturkewi** [comment]
Hey all! Sorry, as @DakotaLMartinez mentioned, the change was made but wasn't deployed to this lab for some reason. It's all set now!
